version: '3.8'

services:
  app:
    build: .
    container_name: fastapi-task-manager
    ports:
      - '8000:8000'
    environment:
      - DATABASE_URL=\
      - SECRET_KEY=\
      - ALGORITHM=\
      - ACCESS_TOKEN_EXPIRE_MINUTES=\
      - REDIS_URL=\
      - LOG_LEVEL=\
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=tasks
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: